source 'https://github.com/CocoaPods/Specs.git'

target 'VisualConstraints', :exclusive => true do
  pod "VisualConstraints", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "VisualConstraints", :path => "../"

  pod 'FBSnapshotTestCase'
end
